const players = [
    {
        player_name: "Brad",
        character_name: "Twinklestar",
        class: "exquisite",
        life: "7",
        str: "1",
        end: "2",
        agi: "3",
        cha: "4",
        aur: "5",
        tho: "6",
        avatar: "avatar.png"
    },
    {
        player_name: "Cody",
        character_name: "Twinklestar",
        class: "exquisite",
        life: "7",
        str: "1",
        end: "2",
        agi: "3",
        cha: "4",
        aur: "5",
        tho: "6",
        avatar: "avatar.png"
    },
    {
        player_name: "Derek",
        character_name: "Twinklestar",
        class: "exquisite",
        life: "7",
        str: "1",
        end: "2",
        agi: "3",
        cha: "4",
        aur: "5",
        tho: "6",
        avatar: "avatar.png"
    },
    {
        player_name: "Juan",
        character_name: "Twinklestar",
        class: "exquisite",
        life: "7",
        str: "1",
        end: "2",
        agi: "3",
        cha: "4",
        aur: "5",
        tho: "6",
        avatar: "avatar.png"
    },
    {
        player_name: "Keith",
        character_name: "Twinklestar",
        class: "exquisite",
        life: "7",
        str: "1",
        end: "2",
        agi: "3",
        cha: "4",
        aur: "5",
        tho: "6",
        avatar: "avatar.png"
    },
    {
        player_name: "Ryan",
        character_name: "Twinklestar",
        class: "exquisite",
        life: "7",
        str: "1",
        end: "2",
        agi: "3",
        cha: "4",
        aur: "5",
        tho: "6",
        avatar: "avatar.png"
    },
    {
        player_name: "Taylor",
        character_name: "Twinklestar",
        class: "exquisite",
        life: "7",
        str: "1",
        end: "2",
        agi: "3",
        cha: "4",
        aur: "5",
        tho: "6",
        avatar: "avatar.png"
    },
];

module.exports = players;