const players = [
    {
        player_name: "Brad",
        character_name: "Brad",
        class: "Hexad Enforcer Militant",
        life: "6",
        str: "1",
        end: "2",
        agi: "3",
        cha: "4",
        aur: "5",
        tho: "6",
        avatar: "avatar.png"
    },
    {
        player_name: "Cody",
        character_name: "Cody",
        class: "Blueland Smoke Thief",
        life: "4",
        str: "1",
        end: "2",
        agi: "3",
        cha: "4",
        aur: "5",
        tho: "6",
        avatar: "avatar.png"
    },
    {
        player_name: "Derek",
        character_name: "Derek",
        class: "Exiled Liberal Pirate",
        life: "7",
        str: "1",
        end: "2",
        agi: "3",
        cha: "4",
        aur: "5",
        tho: "6",
        avatar: "avatar.png"
    },
    {
        player_name: "Juan",
        character_name: "Juan",
        class: "Amnesiac Wizard Apprentice",
        life: "5",
        str: "1",
        end: "2",
        agi: "3",
        cha: "4",
        aur: "5",
        tho: "6",
        avatar: "avatar.png"
    },
    {
        player_name: "Keith",
        character_name: "Keith",
        class: "High Society Con Artist",
        life: "6",
        str: "1",
        end: "2",
        agi: "3",
        cha: "4",
        aur: "5",
        tho: "6",
        avatar: "avatar.png"
    },
    {
        player_name: "Ryan",
        character_name: "Ryan",
        class: "Boho Witch Monk",
        life: "8",
        str: "1",
        end: "2",
        agi: "3",
        cha: "4",
        aur: "5",
        tho: "6",
        avatar: "avatar.png"
    },
    {
        player_name: "Taylor",
        character_name: "Taylor",
        class: "Scarred Seaman",
        life: "7",
        str: "1",
        end: "2",
        agi: "3",
        cha: "4",
        aur: "5",
        tho: "6",
        avatar: "avatar.png"
    },
];

module.exports = players;